### ISSUE TITLE
6.11. Goal 2 - Gather preliminary (toy) dataset

### ISSUE THREAD

**Issue by phinik** [phinik/LovelyLLamas#4]
Due 6.11.2024

**Comment by Ace-Of-Snakes** [comment]
Pilot Data Set was suposed to be collected today. 
Didn't work out due to a bug -> less valuable Data Set collected. Should be done by tommorow

**Comment by Ace-Of-Snakes** [comment]
Preliminary Data Set Collected with Valuable Data Points, Scheduling needs to be adjusted to multiple times a day for specific region locked data

**Comment by phinik** [comment]
Actually the idea was to collect data for like an entire week, not just a single day

**Comment by phinik** [comment]
Achieved with "debug_dataset" dataset
