### ISSUE TITLE
10.12. Goal 1 - Improve LSTM outputs

### ISSUE THREAD

**Issue by phinik** [phinik/LovelyLLamas#9]
Find inspiration from image captioning?

**Comment by phinik** [comment]
Delayed to the upcoming week due to unexpected work for the data collection

**Comment by nielshannemann** [comment]
First executable LSTM architecture built, now further experimenting with architecture details and adaption to make it more suitable

**Comment by nielshannemann** [comment]
Overhauled training code for easier experimentation, yet unexpected problems delay the original goal

**Comment by nielshannemann** [comment]
Lots of strategies tested, output improves but is still unsatisfying. Unfortunately not done. More specific subgoals: change data preprocessing to focus on most relevant aspects, experiment with attention, implement further punishment for long predictions
